import './styles/global.scss'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({
  subsets: ['latin']
});

export const metadata = {
  title: 'display data retrieved from api',
  description: 'generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
